name: API-POI-CI

on:
  push:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  pull_request:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/poi
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 3.1 
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./apis/poi/web
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./apis/poi/tests/UnitTests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.eventname == 'push' || github.eventname == 'workflow_dispatch' }}
    env:
      working-directory: apis/poi/
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Build the container using ACR task.  The Dockerfile will build and run unit tests.
        inlineScript: |
          cd ${{env.working-directory}}/web
          az acr build --registry openhack4nl2avg0acr --image devopsoh/api-poi:${GITHUB_RUN_NUMBER} .
