# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API-USERPROFILE-CI

on:
  push:
    branches: [ main ]
    paths:
      - './apis/userprofile/**'
  pull_request:
    branches: [ main ]
    paths:
      - './apis/userprofile/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/userprofile
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - run: npm install
    #- run: npm run test
