name: API-POI-CI

on:
  push:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  pull_request:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/poi
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 3.1 
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./apis/poi/web
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./apis/poi/tests/UnitTests
