# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: api-userprofile

on:
  push:
    branches: [ main ]
    paths:
      - './apis/userprofile/**'
  pull_request:
    paths:
      - './apis/userprofile/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/userprofile
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - run: npm install
    #- run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    env:
      working-directory: apis/userprofile/
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Build the container using ACR task.  The Dockerfile will build and run unit tests.
        inlineScript: |
          cd ${{env.working-directory}}
          az acr build --registry openhack4nl2avg0acr --build-arg ${{ github.sha }} --image devopsoh/api-userprofile:${{ github.sha }} .
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'openhack4nl2avg0userprofile'
        images: 'openhack4nl2avg0acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}'
