# This workflow contains global base checks

name: base-checks

# Controls when the workflow will run
on: pull_request
    
jobs:
  # Build job for base checks
  basecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Assigns an author to the PR
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
