name: API-TRIPS-CI

on:
  push:
    branches: [ main ]
    paths:
      - './apis/trips/**'
  pull_request:
    branches: [ main ]
    paths:
      - './apis/trips/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/trips
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.11.1
        
    - name: Test
      run: go test ./tripgo -run Unit
