name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  pull_request:
    branches: [ main ]
    paths:
      - './apis/poi/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/poi
    steps:
    - uses: actions/checkout@v2
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Build the container using ACR task.  The Dockerfile will build and run unit tests.
        inlineScript: |
          az acr build --registry openhack4nl2avg0acr --image devopsoh/api-poi:${GITHUB_RUN_NUMBER} --file Dockerfile ./web
     
